apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: es-elasticsearch
    chart: "elasticsearch-0.2.2"
    release: "es"
    heritage: "Tiller"
    component: es-elasticsearch
    role: client
spec:
  type: LoadBalancer
  selector:
    component: es-elasticsearch
    role: client
  ports:
  - name: http
    port: 9200
    targetPort: 9200
    protocol: TCP
    nodePort: 32000
  - name: transport
    port: 9300
    targetPort: 9300
    protocol: TCP
#type: LoadBalancer
#test
