apiVersion: v2
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    app: es-elasticsearch
    chart: "elasticsearch-0.2.2"
    release: "es"
    heritage: "Tiller"
    component: es-elasticsearch
    role: master
spec:
  selector:
    component: es-elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  #clusterIP: None

