apiVersion: true
kind: Deployment
metadata:
  labels:
    app: es-elasticsearch
    chart: elasticsearch-0.2.2
    component: es-elasticsearch
    heritage: Tiller
    release: es
    role: client
  name: es-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: es-elasticsearch
        release: es
        role: client
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISCOVERY_SERVICE
              value: elasticsearch-discovery
            - name: CLUSTER_NAME
              value: profile_cluster
            - name: NODE_MASTER
              value: 'false'
            - name: NODE_INGEST
              value: 'false'
            - name: NODE_DATA
              value: 'false'
            - name: HTTP_ENABLE
              value: 'true'
            - name: NUMBER_OF_MASTERS
              value: '1'
            - name: NETWORK_HOST
              value: 0.0.0.0
            - name: MAX_LOCAL_STORAGE_NODES
              value: '10'
            - name: HTTP_CORS_ENABLE
              value: 'true'
            - name: HTTP_CORS_ALLOW_ORIGIN
              value: 'true'
            - name: ES_JAVA_OPTS
              value: '-Xms256m -Xmx256m'
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          image: 'girishmaplelabs/elasticsearch:5.4.3'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 120
            successThreshold: 1
            tcpSocket:
              port: 9300
            timeoutSeconds: 10
          name: es-client
          ports:
            - containerPort: 9200
              name: http
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: 20
            timeoutSeconds: 10
          resources:
            requests:
              memory: 256Mi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
            privileged: false
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/es_data
              name: storage
      initContainers:
        - command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144
          image: 'busybox:latest'
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          securityContext:
            privileged: true
      nodeSelector:
        node-role: es_node
      volumes:
        - emptyDir:
            medium: ''
          name: storage
