apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-master
  labels:
    app: es-elasticsearch
    chart: "elasticsearch-0.2.2"
    release: "es"
    heritage: "Tiller"
    component: es-elasticsearch
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        release: "es"
        component: es-elasticsearch
        role: master
    spec:
      nodeSelector:
        node-role: es_node
      initContainers:
      - name: init-sysctl
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: girishmaplelabs/elasticsearch:5.4.3
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: elasticsearch-discovery
        - name: CLUSTER_NAME
          value: "profile_cluster"
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NUMBER_OF_REPLICAS
          value: "1"
        - name: NUMBER_OF_SHARDS
          value: "3"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: MAX_LOCAL_STORAGE_NODES
          value: "10"
        - name: HTTP_CORS_ENABLE
          value: "true"
        - name: HTTP_CORS_ALLOW_ORIGIN
          value: "true"
        - name: ES_JAVA_OPTS
          #value: -Xms4g -Xmx4g
          value: -Xms256m -Xmx256m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            memory: 256Mi
#          limits:
#            cpu: 1
        ports:
        - containerPort: 9200
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 120
          successThreshold: 1
          tcpSocket:
            port: 9300
          timeoutSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /usr/share/elasticsearch/es_data
      #restartPolicy: Always
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
          #- name: elasticdir
          #  hostPath:
          #      path: /data
        
